# Generated by Django 2.1.3 on 2018-11-10 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_content', models.CharField(max_length=200, verbose_name='用户评论')),
                ('comment_nums', models.IntegerField(verbose_name='评论量')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User', verbose_name='用户')),
            ],
            options={
                'db_table': '用户评论',
            },
        ),
        migrations.CreateModel(
            name='UserFavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favor_nums', models.IntegerField(verbose_name='收藏量')),
                ('favor_created_time', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.Blog', verbose_name='博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User', verbose_name='用户')),
            ],
            options={
                'db_table': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=500, verbose_name='消息内容')),
                ('message_send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('message_nums', models.IntegerField(verbose_name='消息量')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User', verbose_name='用户')),
            ],
            options={
                'db_table': '用户消息',
            },
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_nums', models.IntegerField(verbose_name='阅读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
